// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjJbjCgST1lZ008J9QmeHZimwFq-MzdSg',
    appId: '1:392545068869:web:ae1d126c8032cebba8c9be',
    messagingSenderId: '392545068869',
    projectId: 'lenseat-app',
    authDomain: 'lenseat-app.firebaseapp.com',
    storageBucket: 'lenseat-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjJbjCgST1lZ008J9QmeHZimwFq-MzdSg',
    appId: '1:392545068869:android:bbf62046dde08b730e402c',
    messagingSenderId: '392545068869',
    projectId: 'lenseat-app',
    storageBucket: 'lenseat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxP-3j4bQXk58XoQRjqupQEAJOLd230qQ',
    appId: '1:392545068869:ios:864f263e8aac75d00e402c',
    messagingSenderId: '392545068869',
    projectId: 'lenseat-app',
    storageBucket: 'lenseat-app.firebasestorage.app',
    androidClientId: '392545068869-6bn3aenuiofsjbi68j8javgos22gv2m8.apps.googleusercontent.com',
    iosClientId: '392545068869-78oe97uor9umtlau3oasjb7qpghu3126.apps.googleusercontent.com',
    iosBundleId: 'com.lenseat.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxP-3j4bQXk58XoQRjqupQEAJOLd230qQ',
    appId: '1:392545068869:ios:864f263e8aac75d00e402c',
    messagingSenderId: '392545068869',
    projectId: 'lenseat-app',
    storageBucket: 'lenseat-app.firebasestorage.app',
    androidClientId: '392545068869-6bn3aenuiofsjbi68j8javgos22gv2m8.apps.googleusercontent.com',
    iosClientId: '392545068869-78oe97uor9umtlau3oasjb7qpghu3126.apps.googleusercontent.com',
    iosBundleId: 'com.lenseat.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjJbjCgST1lZ008J9QmeHZimwFq-MzdSg',
    appId: '1:392545068869:web:ae1d126c8032cebba8c9be',
    messagingSenderId: '392545068869',
    projectId: 'lenseat-app',
    authDomain: 'lenseat-app.firebaseapp.com',
    storageBucket: 'lenseat-app.firebasestorage.app',
  );
}
