// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByhaMYpLAtkhdGqplfxllMNjHjqsWcCvk',
    appId: '1:808142209819:web:ae1d126c8032cebba8c9be',
    messagingSenderId: '808142209819',
    projectId: 'nutrilens-app-ae2ab',
    authDomain: 'nutrilens-app-ae2ab.firebaseapp.com',
    storageBucket: 'nutrilens-app-ae2ab.firebasestorage.app',
    measurementId: 'G-X00KFWPLR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbYOIiRU2Hr6NLAWUfJZcAhxq5Etu4Bxk',
    appId: '1:808142209819:android:9e27aa6353807197a8c9be',
    messagingSenderId: '808142209819',
    projectId: 'nutrilens-app-ae2ab',
    storageBucket: 'nutrilens-app-ae2ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6xXoWCB_7lBQQJLYvQTBUqBnpy--hXqA',
    appId: '1:808142209819:ios:64af1cff4b089e65a8c9be',
    messagingSenderId: '808142209819',
    projectId: 'nutrilens-app-ae2ab',
    storageBucket: 'nutrilens-app-ae2ab.firebasestorage.app',
    androidClientId: '808142209819-hppu90dfelcvo4bejjsptf39vmalkltd.apps.googleusercontent.com',
    iosClientId: '808142209819-5qrdgha994qpksdqqibu26q939vsi8jm.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutriLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6xXoWCB_7lBQQJLYvQTBUqBnpy--hXqA',
    appId: '1:808142209819:ios:64af1cff4b089e65a8c9be',
    messagingSenderId: '808142209819',
    projectId: 'nutrilens-app-ae2ab',
    storageBucket: 'nutrilens-app-ae2ab.firebasestorage.app',
    androidClientId: '808142209819-hppu90dfelcvo4bejjsptf39vmalkltd.apps.googleusercontent.com',
    iosClientId: '808142209819-5qrdgha994qpksdqqibu26q939vsi8jm.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutriLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByhaMYpLAtkhdGqplfxllMNjHjqsWcCvk',
    appId: '1:808142209819:web:ad6fdd828890ab8ea8c9be',
    messagingSenderId: '808142209819',
    projectId: 'nutrilens-app-ae2ab',
    authDomain: 'nutrilens-app-ae2ab.firebaseapp.com',
    storageBucket: 'nutrilens-app-ae2ab.firebasestorage.app',
    measurementId: 'G-X57JFJYD31',
  );
}
